language: r
sudo: false
warnings_are_errors: false
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - testthat

r_github_packages:
  - jimhester/covr

after_success:
- Rscript -e 'covr::codecov()'
